title:             MachineMan Blog
email:             machineman7777@gmail.com
description:       
author:            MachineMan
url:               "http://machineman7777.github.io"

# Social Profiles
github_username:   machineman7777

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
